### PR TITLE
Update Components, fix lint errors, fix bugs and other improvements

### LINKED ISSUE #98: Use Map Card and/or Map Card like design in the search dropdowns
Currently, the search will display results for Maps and Playlists in a "dropdown".

These are pretty simple so far and their accompanying image is quite small. They might be redesigned to look more like the Map Cards.

This task would be completed, when:

- The Map Search has an improved design
- The Playlist Search has an improved design

This may be very well split in two tasks and PRs as well.

### LINKED ISSUE #140: Add contributors to author box
See the conversation here: https://github.com/beastsaber/bsaber/pull/138#discussion_r1606094152

### LINKED ISSUE #141: Multiple authors are not displayed
When multiple authors are provided on an article only the first is displayed.
This came up with #140, but no immediate solution or cause was found.

### PR DESCRIPTION
**Pull request by michael-r-elp**
With the initial migration to svelte 5 now done, this PR aims to migrate and improve some components as well as do a general look at the whole codebase for potential eslint errors that require looking into.

### Improvements
* Use BeatSaverClientFactory in search bar
* Use await block in search bar, allows for displaying a message depending on the promise state
* Adds prettierignore as second ignore source for eslint
* Better search preview card, now includes diffs design might close #98 
* Added contributions, closes #140 
* Added ErrorHandler component to catch components that might break the whole page (shows error component instead)

### Components Updates
* Updated the following components to svelte 5 syntax
  - Navbar, Search, MapCards, MapPreview, OneClickDownloadButton, PlaylistCards, PostPage
* Improved Search component

### Fixed Lint errors
* Added keys to all "each" blocks see [require-each-key](https://sveltejs.github.io/eslint-plugin-svelte/rules/require-each-key/) and [keyed-each-blocks](https://svelte.dev/docs/svelte/each#Keyed-each-blocks) for more information 
(technically we don't use anything that requires this I believe, but eslint complains about it so I just add keys)

### Fixed bugs
* Closes #141 

Also I think with us using svelte 5 now, this opens up the possibility to also improve the way certain parts of the website work, but that might be beyond the scope of this PR.

Discussion as well as suggestions about any changes made would be appreciated

### CODE REVIEW

File: src/lib/PaginationBar.svelte [hunk 1]
```diff
@@ -20,7 +20,7 @@
   >
     <Fa icon={faAngleLeft} />
   </a>
-  {#each pageNumbers as singlePageNumber}
+  {#each pageNumbers as singlePageNumber (singlePageNumber)}
```
Comment (TimothyGillespie) [inline src/lib/PaginationBar.svelte:23]: Perhaps the current page number with a separate symbol would be more reliable in cases of SPA like navigation. Not sure, though.

File: src/lib/Search.svelte [hunk 2]
```diff
@@ -3,7 +3,35 @@
...
+    }
+  }
+
+  interface PlaylistWithStats extends Playlist {
+    stats: {
+      upVotes: number
+      downVotes: number
+      avgScore: number
+    }
+  }
```
Comment (TimothyGillespie) [inline src/lib/Search.svelte:34]: NIce! Feel free organize the typing files differently as well since they became one large monolith.

File: src/lib/Search.svelte [hunk 3]
```diff
@@ -26,35 +54,27 @@
...
-    nsfw?: boolean
-  }[] = []
+  let previewResults: Preview[] = $state([])
 
   let searchPreviewTimeout: string | number | NodeJS.Timeout | undefined
   let searchButton: HTMLAnchorElement
-  let searchUrl: string
+  let searchUrl: string = $state('')
+
+  let beatSaverPromise: Promise<any> | undefined = $state()
```
Comment (TimothyGillespie) [inline src/lib/Search.svelte:77]: The type could possible be derived from the function. But doesn't have to be. Just an idea.

File: src/routes/posts/search/+page.svelte [hunk 4]
```diff
@@ -37,7 +37,7 @@
 
 <h1>Article Search</h1>
 <div class="cards">
-  {#each posts as post}
+  {#each posts as post (post)}
```
Comment (TimothyGillespie) [inline src/routes/posts/search/+page.svelte:40]: This doesn't seem right. Does this work to pass in a whole object in svelte 5?

File: src/lib/Leaderboard.svelte [hunk 5]
```diff
@@ -22,7 +22,8 @@
 </script>
 
 <Listing {title} {img} {linkText} {linkUrl}>
-  {#each players as player, index}
+  <!-- Using player.name as key but ideally it should be some kind of uid -->
+  {#each players as player (player.name)}
```
[the remark this answers is not in the document]
Comment (michael-r-elp) [reply src/lib/Leaderboard.svelte:26]: Well I have found out that while they recommend to use a string or number as key, it's also possible to just use the object itself, so I might change it to that in places like here

File: src/routes/posts/search/+page.svelte (hunk 4 above)
Comment (michael-r-elp) [reply src/routes/posts/search/+page.svelte:40]: Yes apparently it does, though not recommended according to the docs https://svelte.dev/docs/svelte/each#Keyed-each-blocks

> If a key expression is provided — which must uniquely identify each list item — Svelte will use it to diff the list when data changes, rather than adding or removing items at the end. The key can be any object, but strings and numbers are recommended since they allow identity to persist when the objects themselves change.

File: src/lib/Search.svelte (hunk 3 above)
Comment (michael-r-elp) [reply src/lib/Search.svelte:77]: The type is the Preview type I have at the top, just forgot to replace this

**Comment by michael-r-elp** [comment]
Changed the buttons on the map/playlist cards, basically if a device doesn't support hover for example a tablet we always display the buttons if the available space on the screen allows for it.

What I'm not sure about right now is whether the oneclick download buttons should be displayed on non-hover capable devices or not. I can't really imagine a touch screen device where you'd use one click downloads on, except maybe one of those windows tablets, also I'm unsure on the behaviour if a device has both a mouse and touchscreen, I believe it would be considered hover capable maybe? Could probably test by plugging in a mouse into a smartphone and tablet and see how it reacts.

**Comment by michael-r-elp** [comment]
I'll mark this ready for review now, as there are quite a lot of changes in here now.

And I unfortunately lack the time to do more in-depth work on this, so I rather get what we have done and merged and someone else or if I happen to have time again will have to go through everything and make improvements as well as update remaining components to svelte 5 syntax where necessary.

**Comment by TheCzar1994** [comment]
I will try to take a look at this as well at some point this week - hopefully tomorrow

**Comment by TheCzar1994** [comment]
Looks like the Featured Playlists page is broken. I'm just getting a gray screen.
https://deploy-preview-222--bsaber.netlify.app/playlists/page/1

**Comment by michael-r-elp** [comment]
> Looks like the Featured Playlists page is broken. I'm just getting a gray screen. https://deploy-preview-222--bsaber.netlify.app/playlists/page/1
> 
> I haven't looked at any code yet but wanted to note other things I find here for when I do:
> 
> * Featured Playlist cards on homepage don't have download buttons on mobile/touch screens where MapCards and MOTW do. This seems inconsistent.
> * MapCard song preview hover seems to either duplicate the background color causing a border or there is some border issue or perhaps before/after issue?

That should all be fixed now.

The page broke again because I thought I could remove the workaround if I have the elements nested inside another div, but turns out that only works for the front page playlists somehow.

Added the download buttons to the playlists for mobile, though they seem quite small so idk how usable they actually end up beeing, at least it's consistent now.

For the MapCard Song Audio Preview, I think I changed it to a button element at some point and didn't properly account for any default styles that come with it, I fixed that now, disabled the border and box shadow style that the browser adds.

**Comment by michael-r-elp** [comment]
For additional safety where a component erroring might break the whole site, I added a handler component and used a svelte:boundary for the playlistscards in the playlists page this can be useful in case the problem occours again, while also showing some helpful information for debugging.

Usage:
```svelte
<script>
  import ErrorHandler from '$lib/ErrorHandler.svelte'
</script>

<svelte:boundary>
  <FlakyComponent />

  {#snippet failed(error, reset)}
    <ErrorHandler
      error={error}
      reset={reset}
    />
  {/snippet}
</svelte:boundary>
```

See above image example of the ErrorHandler.svelte Component

image


I don't expect people to really come accross this, but it's there now in case we run into a problem again.

File: src/lib/MapOfTheWeekSection.svelte [hunk 6]
```diff
@@ -119,9 +119,9 @@
               </button>
             {/if}
             <div class="interactive-buttons">
-              <CopyBsr mapId={mapOfTheWeek.map.id} />
```
Comment (TheCzar1994) [inline src/lib/MapOfTheWeekSection.svelte:122]: I'm confused why this change is here? Swapping these around and adding the `direction: rtl` to the styling actually causes an uneven spacing change to these buttons
With rtl (uneven spacing)
image
Without rtl (even spacing)
image

Comment (michael-r-elp) [reply src/lib/MapOfTheWeekSection.svelte:122]: Because on touch devices some buttons are hidden, leaving an empty space where the button would be, this was one possible solution for it.

Comment (michael-r-elp) [reply src/lib/MapOfTheWeekSection.svelte:122]: The uneven spacing seems to be because the actual svg within the a element is not centered.
I'll see about fixing it later if I remember.

Comment (TheCzar1994) [reply src/lib/MapOfTheWeekSection.svelte:122]: This looks fine, thanks! Sorry it's taken so long to get this reviewed. Will try my best to get it done this week!! Or hopefully even still tonight!

File: src/lib/Search.svelte [hunk 7]
```diff
@@ -135,15 +179,25 @@
...
+
+  // Ideally I'd do the below using CSS but
+  // the svelte compiler seems to remove these css classes
+
+  // Function to calculate color based on percentage takes percentage as float
+  function getGradientColor(rating: float) {
+    // Map rating percentage (0-100) to hue range (0 = red, 120 = green)
+    const hue = rating * 120 // 0% = red, 100% = green
+    return `hsl(${hue}, 100%, 50%)` // Full saturation and 50% lightness
+  }
```
Comment (TheCzar1994) [inline src/lib/Search.svelte:191]: I've got to be honest; I'm not a huge fan of how this looks. There were complaints previously about the color coding of ratings on BeatSaver and I'd prefer to avoid that drama. However, I'm also unsure of how else to represent it so not sure how to go about this. Perhaps just a flat color? We've already got the color coded CaretUp and CaretDown

File: src/routes/community-hub/+page.svelte [hunk 8]
```diff
@@ -2,18 +2,18 @@
...
+  //   faFacebook,
+  //   faInstagram,
+  //   faTwitch,
+  //   faXTwitter,
+  //   faYoutube,
+  //   faReddit,
+  //   faGithub,
+  // } from '@fortawesome/free-brands-svg-icons'
+  // import { faLink, faBook } from '@fortawesome/free-solid-svg-icons'
+  // import Fa from 'svelte-fa'
```
Comment (TheCzar1994) [inline src/routes/community-hub/+page.svelte:16]: Looks like these can be removed instead of commented out?

File: src/routes/playlists/eminem-pack/AlbumPlaylistCard.svelte [hunk 9]
```diff
@@ -1,7 +1,7 @@
 <script lang="ts">
   import MapCards from '$lib/MapCards.svelte'
   import OneClickDownloadButton from '$lib/OneClickDownloadButton.svelte'
-  import SocialIcon from '$lib/SocialIcon.svelte'
+  // import SocialIcon from '$lib/SocialIcon.svelte'
```
Comment (TheCzar1994) [inline src/routes/playlists/eminem-pack/AlbumPlaylistCard.svelte:4]: Can remove this if not needed

File: src/routes/playlists/love-live-birthday-pack/AlbumPlaylistCard.svelte [hunk 10]
```diff
@@ -6,7 +6,7 @@
   export let groupName: string
   export let playlistId: number
 
-  const playlistUrl = `https://api.beatsaver.com/playlists/id/${playlistId}/download/beatsaver-${playlistId}.bplist`
+  // const playlistUrl = `https://api.beatsaver.com/playlists/id/${playlistId}/download/beatsaver-${playlistId}.bplist`
```
Comment (TheCzar1994) [inline src/routes/playlists/love-live-birthday-pack/AlbumPlaylistCard.svelte:9]: Can remove if not needed

**Review by TheCzar1994 — COMMENTED** [review]
Overall, this looks good to me. I especially like the revisions to the search bar so thank you for your work on that! I left a few mostly minor comments. I would still like to review this more on mobile/touch devices and perhaps on my Quest, though, with BMBF being deprecated I'm unsure how much Quest users need to be able to have the buttons anyways.

Looks like there's still some open comments from @TimothyGillespie too?

File: src/lib/Difficulties.svelte [hunk 11]
```diff
@@ -45,6 +45,7 @@
     align-items: center;
     font-size: 0.75rem;
     user-select: none;
+    // container-type: inline-size;
```
[the remark this answers is not in the document]
Comment (michael-r-elp) [reply src/lib/Difficulties.svelte:48]: It was added and then commented out, there's some issue with the style of the difficulties at certain breakpoints since they're intended for use in map cards that at certain sizes are next to each other.

File: src/lib/Difficulties.svelte [hunk 12]
```diff
@@ -154,6 +155,10 @@
     display: none;
   }
 
+  // Switch to the below whenever there's proper support for it in svelte/sass
+  // @container (width > 650px) {
+
+  // Find a solution for the below that also properly works for search cards
```
[the remark this answers is not in the document]
Comment (michael-r-elp) [reply src/lib/Difficulties.svelte:161]: Yeah relates to my above comment about sizing in map cards unfortunately `@container` didn't seem to be supported in sass.

File: src/lib/Search.svelte (hunk 7 above)
Comment (TheCzar1994) [reply src/lib/Search.svelte:191]: To be fair, the initial complaints on the BeatSaver side were with the pill style rating bar below the album covers which are now orange and green. It used to be red and green - and when there were more downvotes than upvotes, the red would overtake the space and would cause morale issues for some people. I suppose that is different than this and is unlikely to cause anywhere near as much of an issue.

I guess at the end of the day, I'm not entirely opposed to this and I also don't have another answer to it either, so I'm fine with merging this as is and perhaps we can look at it again later if needed.

File: src/lib/Search.svelte (hunk 2 above)
Comment (michael-r-elp) [reply src/lib/Search.svelte:45]: This will probably have to be done in a separate PR by anyone who has some time and a rough idea on how to organize everything

Comment (michael-r-elp) [reply src/lib/Search.svelte:45]: This will probably have to be done in a separate PR by anyone who has some time and a rough idea on how to organize everything

File: src/lib/MapCards.svelte [hunk 13]
```diff
@@ -205,22 +241,50 @@
...
     );
-    background-size: $background-size;
+
+    &:hover {
+      background: linear-gradient(
+        90deg,
+        $color-background-primary $gradient-start,
+        $color-background-tertiary 100%
+      );
+    }
```
Comment (TheCzar1994) [inline src/lib/MapCards.svelte:253]: Sorry, hopefully last few comments before I'm good with this...
It looks like this is causing a duplication of the effect on desktop. I deleted the:
```
   background: linear-gradient(
      90deg,
      $color-background-primary $gradient-start,
      $color-background-secondary 100%
    );
```

above this but I'm guessing that will cause issues with it on touch/mobile since you/we want it to have that normally there? I honestly don't know how to test it on touch devices so not sure what the best fix would be.

File: src/lib/PlaylistCards.svelte [hunk 14]
```diff
@@ -85,16 +88,31 @@
...
-    right: 0.3rem;
-    padding: 0.3rem;
+    display: none;
   }
 
   a .zip-download-button-container {
-    right: 2.5rem;
-    padding: 0.3em 0.45em;
+    right: 0.3rem;
+    padding: 0.3rem;
```
Comment (TheCzar1994) [inline src/lib/PlaylistCards.svelte:96]: Again, hard to test without knowing a good way to test on touch devices but I think this change causes the button to not be a circle on touch devices? 
IMG_0213

File: src/lib/MapCards.svelte (hunk 13 above)
Comment (michael-r-elp) [reply src/lib/MapCards.svelte]: Can you go a bit more into detail what you mean with duplication, it looks basically the same for me, except that I missed the `background-size: 160%` on hover for desktop, which makes the border slightly less prominent when hovering over, but otherwise it looks basically the same as on the production site to me

## Desktop:
### This PR with hover and not hover, plus the change I mentioned:
image

### Production Page:
image


## Mobile:
### This PR:
image

### Production Page:
image

File: src/lib/PlaylistCards.svelte (hunk 14 above)
Comment (michael-r-elp) [reply src/lib/PlaylistCards.svelte:96]: Oh yeah, that one was my mistake should be `padding: .3em .45em;` I'll fix that

**Review by TheCzar1994 — APPROVED** [review]
